# Generated by Django 4.2.9 on 2026-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('add', '增加'), ('deduct', '扣除')], max_length=20)),
                ('points', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
