# Generated by Django 4.2.9 on 2026-04-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0003_prize_prizeexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(verbose_name='变动额度')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('change_type', models.CharField(choices=[('checkin', '每日签到'), ('upload', '资源上传奖励'), ('post', '论坛发帖奖励'), ('exchange', '礼品兑换扣除'), ('admin', '管理员操作')], max_length=20, verbose_name='变动类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='prizeexchange',
            name='points_spent',
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=models.TextField(verbose_name='奖品描述'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='prizeexchange',
            name='exchange_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='兑换日期'),
        ),
        migrations.AlterField(
            model_name='prizeexchange',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.prize', verbose_name='兑换奖品'),
        ),
        migrations.AlterField(
            model_name='prizeexchange',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='prizeexchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='兑换用户'),
        ),
        migrations.DeleteModel(
            name='PointsRecord',
        ),
    ]
