# Generated by Django 4.2.9 on 2026-04-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_add_prize_is_active'),
        ('points', '0005_checkinrecord'),
    ]

    operations = [
    ]
