# Generated by Django 4.2.9 on 2026-03-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='courseresource',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='拒绝原因'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='description',
            field=models.TextField(blank=True, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='file_url',
            field=models.URLField(blank=True, verbose_name='文件地址'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='points_required',
            field=models.IntegerField(default=0, verbose_name='所需积分'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('active', '已发布')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='上传老师'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='title',
            field=models.CharField(max_length=200, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传日期'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursetype', verbose_name='课程类型'),
        ),
    ]
