# Generated by Django 4.2.9 on 2026-03-11 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_coursetype_courseresource_reject_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资源名称')),
                ('description', models.TextField(blank=True, verbose_name='资源描述')),
                ('file_url', models.URLField(blank=True, verbose_name='文件地址')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图片')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='上传日期')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载次数')),
                ('points_required', models.IntegerField(default=0, verbose_name='所需积分')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('active', '已发布')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('is_second_hand', models.BooleanField(default=False, verbose_name='是否二手')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='courses.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='ResourceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='资源类型名称')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='courseresource',
            name='type',
        ),
        migrations.DeleteModel(
            name='CourseCollection',
        ),
        migrations.DeleteModel(
            name='CourseComment',
        ),
        migrations.DeleteModel(
            name='CourseResource',
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='courses.resourcetype', verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL, verbose_name='上传用户'),
        ),
    ]
