# Generated by Django 4.2.9 on 2026-04-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_resource_resourcecollection_resourcecomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='资源评分'),
        ),
        migrations.AddField(
            model_name='resource',
            name='rating_count',
            field=models.IntegerField(default=0, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='user_rating',
            field=models.IntegerField(default=5, verbose_name='用户评分'),
        ),
        migrations.CreateModel(
            name='ResourceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ad', '垃圾广告'), ('copy', '侵权内容'), ('bad', '内容违规'), ('other', '其他原因')], max_length=20, verbose_name='举报原因')),
                ('description', models.TextField(blank=True, verbose_name='详细说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('ignored', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.resource', verbose_name='举报资源')),
            ],
        ),
    ]
