# Generated by Django 4.2.9 on 2026-03-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='visible_to',
            field=models.CharField(choices=[('all', '公开'), ('student', '学生'), ('teacher', '老师')], default='all', max_length=20, verbose_name='可见范围'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
